2024-02-09 13:37:15,679 INFO    MainThread:13480 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-02-09 13:37:15,679 INFO    MainThread:13480 [wandb_setup.py:_flush():76] Configure stats pid to 13480
2024-02-09 13:37:15,679 INFO    MainThread:13480 [wandb_setup.py:_flush():76] Loading settings from C:\Users\heefj\.config\wandb\settings
2024-02-09 13:37:15,679 INFO    MainThread:13480 [wandb_setup.py:_flush():76] Loading settings from c:\Users\heefj\OneDrive\Documents\kaggle\birds\wandb\settings
2024-02-09 13:37:15,679 INFO    MainThread:13480 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-02-09 13:37:15,679 INFO    MainThread:13480 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-02-09 13:37:15,680 INFO    MainThread:13480 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-09 13:37:15,680 INFO    MainThread:13480 [wandb_init.py:_log_setup():526] Logging user logs to c:\Users\heefj\OneDrive\Documents\kaggle\birds\wandb\run-20240209_133715-py3h3xrc\logs\debug.log
2024-02-09 13:37:15,680 INFO    MainThread:13480 [wandb_init.py:_log_setup():527] Logging internal logs to c:\Users\heefj\OneDrive\Documents\kaggle\birds\wandb\run-20240209_133715-py3h3xrc\logs\debug-internal.log
2024-02-09 13:37:15,681 INFO    MainThread:13480 [wandb_init.py:init():566] calling init triggers
2024-02-09 13:37:15,681 INFO    MainThread:13480 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.001, 'epochs': 10, 'batch_size': 32}
2024-02-09 13:37:15,681 INFO    MainThread:13480 [wandb_init.py:init():591] re-initializing run, found existing run on stack: 0pthwpun
2024-02-09 13:37:15,683 INFO    MainThread:13480 [wandb_run.py:_finish():1970] finishing run heefjones/bird classification/0pthwpun
2024-02-09 13:37:15,837 INFO    MainThread:13480 [jupyter.py:save_history():445] not saving jupyter history
2024-02-09 13:37:15,838 INFO    MainThread:13480 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-02-09 13:37:15,838 INFO    MainThread:13480 [wandb_init.py:_jupyter_teardown():454] cleaning up jupyter logic
2024-02-09 13:37:15,838 INFO    MainThread:13480 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 0
2024-02-09 13:37:15,838 INFO    MainThread:13480 [wandb_run.py:_restore():2193] restore
2024-02-09 13:37:15,838 INFO    MainThread:13480 [wandb_run.py:_restore():2199] restore done
2024-02-09 13:37:19,188 INFO    MainThread:13480 [wandb_run.py:_footer_history_summary_info():3866] rendering history
2024-02-09 13:37:19,188 INFO    MainThread:13480 [wandb_run.py:_footer_history_summary_info():3898] rendering summary
2024-02-09 13:37:19,193 INFO    MainThread:13480 [wandb_run.py:_footer_sync_info():3825] logging synced files
2024-02-09 13:37:19,724 INFO    MainThread:13480 [wandb_init.py:init():616] starting backend
2024-02-09 13:37:19,725 INFO    MainThread:13480 [wandb_init.py:init():620] setting up manager
2024-02-09 13:37:19,731 INFO    MainThread:13480 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-02-09 13:37:19,732 INFO    MainThread:13480 [wandb_init.py:init():628] backend started and connected
2024-02-09 13:37:19,751 INFO    MainThread:13480 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-02-09 13:37:19,751 INFO    MainThread:13480 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-02-09 13:37:19,751 INFO    MainThread:13480 [wandb_init.py:init():720] updated telemetry
2024-02-09 13:37:19,789 INFO    MainThread:13480 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-02-09 13:37:20,715 INFO    MainThread:13480 [wandb_run.py:_on_init():2262] communicating current version
2024-02-09 13:37:21,091 INFO    MainThread:13480 [wandb_run.py:_on_init():2271] got version response 
2024-02-09 13:37:21,091 INFO    MainThread:13480 [wandb_init.py:init():804] starting run threads in backend
2024-02-09 13:37:21,225 INFO    MainThread:13480 [wandb_run.py:_console_start():2241] atexit reg
2024-02-09 13:37:21,225 INFO    MainThread:13480 [wandb_run.py:_redirect():2096] redirect: wrap_raw
2024-02-09 13:37:21,225 INFO    MainThread:13480 [wandb_run.py:_redirect():2161] Wrapping output streams.
2024-02-09 13:37:21,225 INFO    MainThread:13480 [wandb_run.py:_redirect():2186] Redirects installed.
2024-02-09 13:37:21,226 INFO    MainThread:13480 [wandb_init.py:init():847] run started, returning control to user process
2024-02-09 15:25:42,341 INFO    MainThread:13480 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-02-09 15:25:42,341 INFO    MainThread:13480 [wandb_setup.py:_flush():76] Configure stats pid to 13480
2024-02-09 15:25:42,342 INFO    MainThread:13480 [wandb_setup.py:_flush():76] Loading settings from C:\Users\heefj\.config\wandb\settings
2024-02-09 15:25:42,342 INFO    MainThread:13480 [wandb_setup.py:_flush():76] Loading settings from c:\Users\heefj\OneDrive\Documents\kaggle\birds\wandb\settings
2024-02-09 15:25:42,342 INFO    MainThread:13480 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-02-09 15:25:42,342 INFO    MainThread:13480 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-02-09 15:25:42,342 INFO    MainThread:13480 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-09 15:25:42,343 INFO    MainThread:13480 [wandb_init.py:_log_setup():526] Logging user logs to c:\Users\heefj\OneDrive\Documents\kaggle\birds\wandb\run-20240209_152542-thpd1tga\logs\debug.log
2024-02-09 15:25:42,343 INFO    MainThread:13480 [wandb_init.py:_log_setup():527] Logging internal logs to c:\Users\heefj\OneDrive\Documents\kaggle\birds\wandb\run-20240209_152542-thpd1tga\logs\debug-internal.log
2024-02-09 15:25:42,343 INFO    MainThread:13480 [wandb_init.py:_jupyter_setup():472] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x0000013990FDCAC0>
2024-02-09 15:25:42,344 INFO    MainThread:13480 [wandb_init.py:init():566] calling init triggers
2024-02-09 15:25:42,344 INFO    MainThread:13480 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.001, 'epochs': 10, 'batch_size': 32}
2024-02-09 15:25:42,344 INFO    MainThread:13480 [wandb_init.py:init():591] re-initializing run, found existing run on stack: py3h3xrc
2024-02-09 15:25:42,346 INFO    MainThread:13480 [wandb_run.py:_finish():1970] finishing run heefjones/bird classification/py3h3xrc
2024-02-09 15:25:42,346 INFO    MainThread:13480 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 0
2024-02-09 15:25:42,346 INFO    MainThread:13480 [wandb_run.py:_restore():2193] restore
2024-02-09 15:25:42,346 INFO    MainThread:13480 [wandb_run.py:_restore():2199] restore done
2024-02-09 15:25:45,842 INFO    MainThread:13480 [wandb_run.py:_footer_history_summary_info():3866] rendering history
2024-02-09 15:25:45,842 INFO    MainThread:13480 [wandb_run.py:_footer_history_summary_info():3898] rendering summary
2024-02-09 15:25:45,846 INFO    MainThread:13480 [wandb_run.py:_footer_sync_info():3825] logging synced files
